apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hotsak-frontend-labs
    team: teamdigihot
  name: hotsak-frontend-labs
  namespace: teamdigihot
spec:
  image: {{image}}
  team: teamdigihot
  port: 3000
  ingresses:
    - https://hotsak.ekstern.dev.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  secureLogs:
    enabled: true
  envFrom:
    - secret: hm-saksbehandling
  env:
    - name: API_URL
      value: ''
    - name: GRUNNDATA_API_URL
      value: ''
    - name: PORT
      value: '3000'
    - name: BRILLEKALKULATOR_API_URL
      value: ''
    - name: CLIENT_ID_HOTSAK_API
      value: ''
    - name: REDIS_HOST
      value: ''
    - name: USE_MSW
      value: 'true'
