apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-saksbehandling-frontend
    team: teamdigihot
  name: hm-saksbehandling-frontend
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 3000
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  #azure:
  #  application:
  #    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true

