apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hotsak-frontend
    team: teamdigihot
  name: hotsak-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  team: teamdigihot
  port: 3000
  ingresses:
    - https://hotsak.intern.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 2
  accessPolicy:
    outbound:
      rules:
        - application: hm-saksbehandling
        - application: hm-grunndata-api
        - application: hm-brille-api
      external: 
        - host: sentry.gc.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "88956569-f23d-455c-ace4-001b56e94602"
          - id: "2f632b40-4730-4692-9c7c-fb744e2d33e1"
    sidecar:
      enabled: true
      autoLogin: false
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  secureLogs:
    enabled: true
  envFrom:
    - secret: hm-saksbehandling
  env:
    - name: API_URL
      value: http://hm-saksbehandling.teamdigihot.svc.cluster.local
    - name: GRUNNDATA_API_URL
      value: http://hm-grunndata-api.teamdigihot.svc.cluster.local
    - name: BRILLEKALKULATOR_API_URL
      value: http://hm-brille-api.teamdigihot.svc.cluster.local
    - name: PORT
      value: '3000'
    - name: CLIENT_ID_HOTSAK_API
      value: api://prod-gcp.teamdigihot.hm-saksbehandling/.default
    - name: REDIS_HOST
      value: saksbehandling-redis.teamdigihot.svc.cluster.local
    - name: USE_MSW
      value: 'false'
    - name: GIT_COMMIT
      value: {{commit}}
