name: Kjør Cypress-tester

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Autentiser med GitHub NPM registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READER_TOKEN }}" >> ~/.npmrc
          echo "@navikt:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Kjør Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://ip6-localhost:3001'
          working-directory: client
          config-file: cypress.config.js
          record: false
          parallel: true
