name: Cypress tests

on: workflow_dispatch
#  push:
#    branches-ignore:
#      - main # deploy-dev.yml har egen cypress test

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://ip6-localhost:3001'
          working-directory: client
          config-file: cypress.config.ts
          record: false
          parallel: true
