name: Cypress Tests

on:
  push:
    branches-ignore:
      - main # deploy-dev.yml har egen cypress test

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: top level install
        run: npm install
      - name: install frontend deps
        run: npm install --prefix client
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev:mock
          wait-on: 'http://localhost:3001'
